In [ ]:
import numpy as np

In [ ]:

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((3, 3))
arr3 = np.ones((3, 3))
arr4 = np.arange(0, 10, 2)
arr5 = np.linspace(0, 10, 5)

print(arr1)
print(arr2)


print(arr3)


print(arr4)
print(arr5)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])


print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


print(np.sqrt(arr1))
print(np.sin(arr1))
print(np.exp(arr1))

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(2, 3)
print(arr)


arr = arr.flatten()
print(arr)


arr = np.array([[1, 2], [3, 4]])
arr = arr.transpose()
print(arr)

(6,)
1
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 3]
 [2 4]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])


print(arr[0])
print(arr[1:3])


mask = arr > 3
print(arr[mask])

indices = np.array([0, 2, 4])
print(arr[indices])

1
[2 3]
[4 5]
[1 3 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])


print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np)

3.0
3.0
1.4142135623730951
2.0
<module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>


In [ ]:
import numpy as np


random_numbers = np.random.rand(5)
print(random_numbers)


random_integers = np.random.randint(0, 10, 5)
print(random_integers)


np.random.seed(42)
random_numbers_seeded = np.random.rand(5)
print(random_numbers_seeded)


array = np.array([1, 2, 3, 4, 5])
random_sample = np.random.choice(array, 3, replace=False)
print(random_sample)

np.random.shuffle(array)
print(array)


permutations = np.random.permutation(array)
print(permutations)


[0.28893773 0.29276461 0.73805375 0.78525019 0.39596504]
[3 2 4 7 1]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[2 1 4]
[1 2 3 4 5]
[1 3 4 2 5]


In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4])
result = array1 + array2
print(result)


array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([7, 8, 9])
result = array1 + array2
print(result)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7], [8]])
result = array1 + array2
print(result)


[5 6 7]
[[ 8 10 12]
 [11 13 15]]
[[ 8  9 10]
 [12 13 14]]
